### ISSUE TITLE
Huge gap in the header

### ISSUE THREAD

**Issue by miyannishar** [miyannishar/inventory-management#2]
![image](https://github.com/user-attachments/assets/5ce033df-38d7-4f21-a12d-1d005ba1aedd)

There is a huge gap between the tile and the top of the web app.

**Comment by GeorgiosDrivas** [comment]
Hello @miyannishar! I would like to work on this issue.

**Comment by miyannishar** [comment]
Hello,

Go ahead, work and open a pull request. You are welcomed!!

Regards,
Nishar Miya
